server:
   port: 18099
#  port: 8080
#  servlet.context-path: /oa

spring:
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss

  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**

  datasource:
    name: shuxiang
    url: jdbc:mysql://127.0.0.1:3306/shuxiang?useUnicode=true&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 10
    maxWait: 600000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


zhsit:
  rdb:
    database: mysql
    schemaPattern: root
  cache:
#serializer type(kryo or jdk with jdk being default)
    redisSerializer: kryo
#缓存有效时间，单位毫秒，默认长久有效,8640000为24小时
    timeToLive: 8640000
  gen:
  # 是否是初始化项目（第一次生成项目)
#    initProject: true
    initProject: false
  # 项目的服务器端java代码编号，同一租户的不要相同,影响生成的文件夹和pom.xml内的artifactId，及
    server: shuxiang
  # 本系统的名称
    systemName: 书香京城
  # 本系统路径
    systemCode: shuxiang
  #系统模板类型
    templateType: layui
  # 数据库名称，影响生成的application.yml中的datasource
    dbName: shuxiang
  # 是否存储到七牛CDN中
    saveQiniu: false
  # 是否存储到FastDFS中
    saveFastDFS: false
  # 是否存储到本机中
    saveLocal: true
  # 是否生成工作流
    workflow: false
  # 是否生成数据库中所有的表
    createAll: false
  # 是否生成测试类
    createTest: true
  # 是否显示注释
    showComment: true
  # ServerApplication路径
    serverApplicationPackage: cn/zhsit/shuxiang
  # 包的根路径
    basePackage: cn/zhsit/shuxiang/gen
  # 注解的路径
    annotationPackage: cn/zhsit/shuxiang/gen/annotations
  #  modle的路径
    modelPackage: cn/zhsit/shuxiang/gen/models
  #  po的路径
    poPackage: cn/zhsit/shuxiang/gen/models/pos
  #  query对象的路径
    queryPackage: cn/zhsit/shuxiang/gen/mappers/querys
  #  remove对象的路径
    removePackage: cn/zhsit/shuxiang/gen/mappers/removes
  #  modify对象的路径
    modifyPackage: cn/zhsit/shuxiang/gen/mappers/modify
  #  provider的路径
    providerPackage: cn/zhsit/shuxiang/gen/mappers/providers
  #  provider的路径
    mapperPackage: cn/zhsit/shuxiang/gen/mappers
  #  manager的路径
    managerPackage: cn/zhsit/shuxiang/gen/manager
  #  managerImpl的路径
    managerImplPackage: cn/zhsit/shuxiang/gen/manager/impl
  #  manager的路径
    servicePackage: cn/zhsit/shuxiang/gen/services
    commonServicePackage: cn/zhsit/shuxiang/gen/services/common
  #  managerImpl的路径
    serviceImplPackage: cn/zhsit/shuxiang/gen/services/impl
    commonServiceImplPackage: cn/zhsit/shuxiang/gen/services/impl/common
  #  Controller的路径
    controllerPackage: cn/zhsit/shuxiang/gen/controllers
  # 通用Controller路径
    commonControllerPackage: cn/zhsit/shuxiang/gen/controllers/common

  # 先做单机版的，默认与工程同级的文件路径，文件夹下按月分开，
  # 做单独的文件微服务。存储到FastDFS中
    filePersistentPath: files
  #  枚举类的路径
    enumPackage: cn/zhsit/shuxiang/gen/enums
  #  Util类的路径
    utilPackage: cn/zhsit/shuxiang/gen/utils
  #  验证码类的路径
    vcodePackage: cn/zhsit/shuxiang/gen/utils/vcode
    # 系统工具类
    systemPackage: cn/zhsit/shuxiang/gen/utils/system
  #  io类的路径
    ioPackage: cn/zhsit/shuxiang/gen/utils/io
  #  处理类的路径
    handlerPackage: cn/zhsit/shuxiang/gen/handlers
  #  过滤类的路径
    filterPackage: cn/zhsit/shuxiang/gen/filters
  #  缓存类的路径
    cachePackage: cn/zhsit/shuxiang/gen/caches
  #  配置类的路径
    configPackage: cn/zhsit/shuxiang/gen/configs
  #  helper类的路径
    helperPackage: cn/zhsit/shuxiang/gen/helpers
  # DFS包路径
    dfsPackage: cn/zhsit/shuxiang/gen/dfs
  # 常量包路径
    constantsPackage: cn/zhsit/shuxiang/gen/constants
  # 拦截器路径
    interceptorPackage: cn/zhsit/shuxiang/gen/interceptors

  # 要生成的表和实体的名称对应,加不加引号都可以
    tableEntity:
      t_role: Role
      t_user: User
      t_user_point: UserPoint
      t_user_role: UserRole
      t_permission: Permission
      t_role_permission: RolePermission
      t_z_menu: ZMenu
      t_role_menu: RoleMenu
      t_soft_system: SoftSystem
      t_activity: Activity
      t_main_type: MainType
      t_location: Location
      t_activity_favorite: ActivityFavorite
      t_activity_comment: ActivityComment
      t_activity_type: ActivityType
      t_activity_screening: ActivityScreening
      t_activity_live: ActivityLive
      t_organization_type: OrganizationType
      t_organization: Organization
      t_organization_favorite: OrganizationFavorite
      t_organization_comment: OrganizationComment
      t_activity_organization_space: ActivityOrganizationSpace
      t_organization_praise: OrganizationPraise
      t_organization_space: OrganizationSpace
      t_organization_user: OrganizationUser
      t_activity_praise: ActivityPraise
      t_activity_reservation: ActivityReservation
      t_activity_reservation_code: ActivityReservationCode
      t_activity_season: ActivitySeason
      t_announcement: Announcement
      t_book: Book
      t_carousel_image: CarouselImage
      t_carousel_location: CarouselLocation
      t_news: News
      t_start_page: StartPage
      t_start_page_image: StartPageImage
      t_user_login: UserLogin
      t_z_file: ZFile


  # 表对象对应类后缀，词尾
    poPostfix:
  #  查询对象后缀
    queryPostfix: Query
  #  删除对象后缀
    removePostfix: Remove
  #  修改对象后缀
    modifyPostfix: Modify
  #  Provider对象
    providerPostfix: Provider
  # 持久类后缀; 词尾
    mapperPostfix: Mapper
  # Manager接口类后缀; 词尾
    managerPostfix: Manager
  # Manager实现类后缀; 词尾
    managerImplPostfix: ManagerImpl
  # 业务接口类后缀; 词尾
    servicePostfix: Service
  # 业务类后缀; 词尾
    serviceImplPostfix: ServiceImpl
  # Controller后缀; 词尾
    controllerPostfix: Controller


#启动图形界面
spring.banner.location:  zhsit.cn.txt
