server:
  port: 80

spring:
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss

  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**

  datasource:
    name: yili
    url: jdbc:mysql://127.0.0.1:3306/biao?useUnicode=true&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 10
    maxWait: 600000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

zhsit:
  rdb:
    database: mysql
    schemaPattern: root

  gen:
  # 是否生成数据库中所有的表
    createAll: false
  # 包的根路径
    basePackage: cn/kuaileniu/gen
  # 注解的路径
    annotationPackage: cn/kuaileniu/gen/annotations
  #  modle的路径
    modelPackage: cn/kuaileniu/gen/models
  #  po的路径
    poPackage: cn/kuaileniu/gen/models/pos
  #  query对象的路径
    queryPackage: cn/kuaileniu/gen/mappers/querys
  #  remove对象的路径
    removePackage: cn/kuaileniu/gen/mappers/removes
  #  modify对象的路径
    modifyPackage: cn/kuaileniu/gen/mappers/modify
  #  provider的路径
    providerPackage: cn/kuaileniu/gen/mappers/providers
  #  provider的路径
    mapperPackage: cn/kuaileniu/gen/mappers
  #  manager的路径
    managerPackage: cn/kuaileniu/gen/manager
  #  managerImpl的路径
    managerImplPackage: cn/kuaileniu/gen/manager/impl
  #  manager的路径
    servicePackage: cn/kuaileniu/gen/service
  #  managerImpl的路径
    serviceImplPackage: cn/kuaileniu/gen/service/impl
  #  枚举类的路径
    enumPackage: cn/kuaileniu/gen/mappers/querys/enums
  # 要生成的table列表,java映射时需要有set和get方法
  #  tableList: [t_order,t_union_key]
    tables:
  # 要生成的表和实体的名称对应,加不加引号都可以
    tableEntity:
      t_amt: Amt
      t_dan_wei_tenderer: DanWeiTenderer
    entityTable:
      Amt: t_amt
      DanWeiTenderer: t_dan_wei_tenderer
  # 表对象对应类后缀，词尾
    poPostfix: PO
  #  查询对象后缀
    queryPostfix: Query
  #  删除对象后缀
    removePostfix: Remove
  #  修改对象后缀
    modifyPostfix: Modify
  #  Provider对象
    providerPostfix: Provider
  # 持久类后缀; 词尾
    mapperPostfix: Mapper
  # Manager接口类后缀; 词尾
    managerPostfix: Manager
  # Manager实现类后缀; 词尾
    managerImplPostfix: ManagerImpl
  # 业务接口类后缀; 词尾
    servicePostfix: Serivce
  # 业务类后缀; 词尾
    serviceImplPostfix: SerivceImpl


#启动图形界面
banner.location:  zhsit.cn.txt
