server:
   port: 18099
#  port: 8080
#  servlet.context-path: /report

spring:
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss

  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**

  datasource:
    name: cypaodm20180723
    url: jdbc:mysql://test-qipai-mysql:3306/cypa-odm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
#    url: jdbc:mysql://127.0.0.1:3306/cypa-odm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: zhsit123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 10
    maxWait: 600000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


zhsit:
  rdb:
    database: mysql
    schemaPattern: root
  cache:
#serializer type(kryo or jdk with jdk being default)
    redisSerializer: kryo
#缓存有效时间，单位毫秒，默认长久有效,8640000为24小时
    timeToLive: 8640000
  gen:
  # 是否是初始化项目（第一次生成项目)
#    initProject: true
    initProject: false
  # 项目的服务器端java代码编号，同一租户的不要相同,影响生成的文件夹和pom.xml内的artifactId，及
    server: cypa-odm
  # 本系统的名称
    systemName: 新派ODM系统
  # 本系统编码
    systemCode: cypa-odm
  #系统模板类型
    templateType: layuiAdmin
  # 数据库名称，影响生成的application.yml中的datasource
    dbName: cypa-odm
  # 是否存储到七牛CDN中
    saveQiniu: false
  # 是否存储到FastDFS中
    saveFastDFS: true
  # 是否存储到本机中
#    saveLocal: true
  # 是否使用poi
    usePOI: true
  # 是否使用lua
    useLua: false
  # 是否使用JFreeChart
    useJFree: false
  # 是否使用 dynamicreports
    useDynamicreports: false
  # 是否使用layui
    useLayui: true
  # 是否使用redis
    useRedis: true
  # 是否使用alain
#    useAlain: true
  # 是否生成工作流
    workflow: true
  # 是否生成数据库中所有的表
    createAll: false
  # 是否生成测试类
    createTest: true
  # 是否显示注释
#    showComment: true
  # ServerApplication路径
    serverApplicationPackage: cn/zhsit/cypaodm
  # 包的根路径
    basePackage: cn/zhsit/cypaodm/gen
  # 注解的路径
    annotationPackage: cn/zhsit/cypaodm/gen/annotations
  #  modle的路径
    modelPackage: cn/zhsit/cypaodm/gen/models
  # layui对应的模型model
    modelLayuiPackage: cn/zhsit/cypaodm/gen/models/layui
  # alain对应的模型model
    modelAlainPackage: cn/zhsit/cypaodm/gen/models/alain
  #  po的路径
    poPackage: cn/zhsit/cypaodm/gen/models/pos
  #  query对象的路径
    queryPackage: cn/zhsit/cypaodm/gen/mappers/querys
  #  remove对象的路径
    removePackage: cn/zhsit/cypaodm/gen/mappers/removes
  #  modify对象的路径
    modifyPackage: cn/zhsit/cypaodm/gen/mappers/modify
  #  provider的路径
    providerPackage: cn/zhsit/cypaodm/gen/mappers/providers
  #  provider的路径
    mapperPackage: cn/zhsit/cypaodm/gen/mappers
  #  manager的路径
    managerPackage: cn/zhsit/cypaodm/gen/manager
  #  managerImpl的路径
    managerImplPackage: cn/zhsit/cypaodm/gen/manager/impl
  #  manager的路径
    servicePackage: cn/zhsit/cypaodm/gen/services
    commonServicePackage: cn/zhsit/cypaodm/gen/services/common
  #  managerImpl的路径
    serviceImplPackage: cn/zhsit/cypaodm/gen/services/impl
    commonServiceImplPackage: cn/zhsit/cypaodm/gen/services/impl/common
  #  Controller的路径
    controllerPackage: cn/zhsit/cypaodm/gen/controllers
  # 通用Controller路径
    commonControllerPackage: cn/zhsit/cypaodm/gen/controllers/common

  # 先做单机版的，默认与工程同级的文件路径，文件夹下按月分开，
  # 做单独的文件微服务。存储到FastDFS中
    filePersistentPath: files
  #  枚举类的路径
    enumPackage: cn/zhsit/cypaodm/gen/enums
  #  Util类的路径
    utilPackage: cn/zhsit/cypaodm/gen/utils
  #  验证码类的路径
    vcodePackage: cn/zhsit/cypaodm/gen/utils/vcode
  # 系统工具类
    systemPackage: cn/zhsit/cypaodm/gen/utils/system
  #  io类的路径
    ioPackage: cn/zhsit/cypaodm/gen/utils/io
  #  office类的路径
    officePackage: cn/zhsit/cypaodm/gen/utils/office
  #  处理类的路径
    handlerPackage: cn/zhsit/cypaodm/gen/handlers
  #  过滤类的路径
    filterPackage: cn/zhsit/cypaodm/gen/filters
  #  缓存类的路径
    cachePackage: cn/zhsit/cypaodm/gen/caches
  #  配置类的路径
    configPackage: cn/zhsit/cypaodm/gen/configs
  #  helper类的路径
    helperPackage: cn/zhsit/cypaodm/gen/helpers
  # DFS包路径
    dfsPackage: cn/zhsit/cypaodm/gen/dfs
  # 常量包路径
    constantsPackage: cn/zhsit/cypaodm/gen/constants
  # 拦截器路径
    interceptorPackage: cn/zhsit/cypaodm/gen/interceptors
  # 异常路径
    exceptionPackage: cn/zhsit/cypaodm/gen/exceptions

  # 要生成的表和实体的名称对应,加不加引号都可以
    tableEntity:
      t_shi_fu: ShiFu
      t_shi_shou: ShiShou
      t_shi_shou_detail: ShiShouDetail
      t_area: Area
      t_ca_auth: CaAuth
      t_order_call_back_log: OrderCallBackLog
      t_carousel_image: CarouselImage
      t_channel: Channel
      t_city: City
      t_cleaning_apply_for: CleaningApplyFor
#      t_complaint: Complaint
      t_customer: Customer
      t_customer_dai_jin_quan: CustomerDaiJinQuan
      t_customer_in_room: CustomerInRoom
      t_invoice_store: InvoiceStore
      t_customer_room_confirm: CustomerRoomConfirm
      t_dai_jin_quan: DaiJinQuan
      t_data_statistics: DataStatistics
      t_device: Device
      t_dict: Dict
      t_dict_module: DictModule
      t_door_control: DoorControl
      t_energy_consumption_price: EnergyConsumptionPrice
      t_equipment: Equipment
      t_equipment_factory: EquipmentFactory
      t_equipment_val_record: EquipmentValRecord
      t_files: Files
      t_gate_door_record: GateDoorRecord
      t_hotel: Hotel
      t_invoice: Invoice
      t_live_his: LiveHis
      t_management_statistics: ManagementStatistics
      t_marketing_activity: MarketingActivity
      t_menu: Menu
      t_menu_permission: MenuPermission
      t_message: Message
      t_moving_apply_for: MovingApplyFor
      t_operating_statistics: OperatingStatistics
      t_org: Org
      t_pay_method: PayMethod
      t_permission: Permission
      t_repair_apply_for: RepairApplyFor
      t_request_log: RequestLog
      t_role: Role
      t_role_menu: RoleMenu
      t_role_permission: RolePermission
      t_role_hotel: RoleHotel
      t_room: Room
      t_room_bill: RoomBill
      t_room_door_record: RoomDoorRecord
      t_room_energy_consumption: RoomEnergyConsumption
      t_room_plan: RoomPlan
      t_room_price: RoomPrice
      t_room_price_his: RoomPriceHis
      t_room_type: RoomType
      t_shou_ju: ShouJu
      t_ying_fu: YingFu
      t_ying_shou: YingShou
      t_ying_shou_detail: YingShouDetail
      t_staff: Staff
      t_staff_role: StaffRole
      t_gate_equipment: GateEquipment
      t_user_gate_equipment: UserGateEquipment
      t_education: Education
      t_orientation: Orientation
      t_msg_tpl: MsgTpl
      t_contract_pic: ContractPic
      t_contract_code: ContractCode
      t_invoice_context: InvoiceContext
      t_he_yue_tpl_val: HeYueTplVal
      t_yu_ding_shen_qing: YuDingShenQing
      t_ru_zhu_shen_qing: RuZhuShenQing
      t_zu_lin_he_yue: ZuLinHeYue
      t_shou_ju_code: ShouJuCode
      t_staff_permission: StaffPermission
      t_staff_menu: StaffMenu
      t_room_type_pic: RoomTypePic
      t_room_type_she_shi: RoomTypeSheShi
      t_shou_ru_level: ShouRuLevel
      t_hang_ye: HangYe
#      t_cleaner: Cleaner
      t_bao_jie_yuan: BaoJieYuan
#      t_hotel_cleaner: HotelCleaner
      t_hotel_bao_jie_yuan: HotelBaoJieYuan
      t_repairman: Repairman
      t_hotel_repairman: HotelRepairman
      t_activity_type: ActivityType
      t_yu_ding_shen_qing_tong_zhu_ren: YuDingShenQingTongZhuRen
      t_ru_zhu_shen_qing_tong_zhu_ren: RuZhuShenQingTongZhuRen
      t_hotel_pic: HotelPic
      t_hotel_she_shi: HotelSheShi
      t_hotel_guan_jia: HotelGuanJia
      t_staff_hotel: StaffHotel
      t_company: Company
      t_ip_map: IpMap
      t_order: Order
      t_mobile_msg: MobileMsg
      t_zhong_qian_log: ZhongQianLog
      t_zhong_qian_code: ZhongQianCode
      t_ri_zhi_type: RiZhiType
      t_ri_zhi: RiZhi
      t_ri_zhi_item: RiZhiItem
      t_ri_zhi_pi_zhu: RiZhiPiZhu
      t_role_group: RoleGroup
      t_role_guan_kong: RoleGuanKong
      t_ri_zhi_item_type: RiZhiItemType
      t_ri_zhi_yun_ying_xin_qian: RiZhiYunYingXinQian
      t_ri_zhi_yun_ying_tui_zu: RiZhiYunYingTuiZu
      t_ri_zhi_yun_ying_xu_zu: RiZhiYunYingXuZu
      t_ri_zhi_yun_ying_kong_fang: RiZhiYunYingKongFang
#      t_ri_zhi_yun_ying_chu_zu_lv: RiZhiYunYingChuZuLv
      t_ri_zhi_yun_ying_jin_dian_deng_ji: RiZhiYunYingJinDianDengJi
      t_ri_zhi_yun_ying_lai_dian_deng_ji: RiZhiYunYingLaiDianDengJi
      t_ri_zhi_yun_ying_tou_su: RiZhiYunYingTouSu
      t_ri_zhi_yun_ying_bao_xiu: RiZhiYunYingBaoXiu
      t_ri_zhi_yun_ying_bao_jie: RiZhiYunYingBaoJie
      t_ri_zhi_yun_ying_qian_fei: RiZhiYunYingQianFei
      t_ri_zhi_yun_ying_gong_qu_dian: RiZhiYunYingGongQuDian
      t_ri_zhi_yun_ying_fa_piao: RiZhiYunYingFaPiao
      t_ri_zhi_yun_ying_fu_kuan_tong_zhi: RiZhiYunYingFuKuanTongZhi
      t_ri_zhi_yun_ying_xun_shi: RiZhiYunYingXunShi
      t_ri_zhi_yun_ying_ri_chang_shi_wu: RiZhiYunYingRiChangShiWu
      t_ri_zhi_yun_ying_jiao_jie: RiZhiYunYingJiaoJie
      t_ri_zhi_yun_ying_zi_jin: RiZhiYunYingZiJin
      t_customer_hotel: CustomerHotel
      t_customer_fa_piao: CustomerFaPiao
      t_customer_shou_ju: CustomerShouJu
      t_ri_zhi_xiao_shou_da_ke_hu: RiZhiXiaoShouDaKeHu
      t_ri_zhi_xiao_shou_zhong_jie: RiZhiXiaoShouZhongJie
      t_ri_zhi_xiao_shou_xun_wen_deng_ji: RiZhiXiaoShouXunWenDengJi
      t_ri_zhi_xiao_shou_ping_tai: RiZhiXiaoShouPingTai
      t_ri_zhi_tong_yong: RiZhiTongYong
      t_gong_zuo_lei_bie: GongZuoLeiBie
      t_gong_zuo_miao_shu: GongZuoMiaoShu
      t_ri_zhi_xiang_mu: RiZhiXiangMu
      t_ri_zhi_yun_ying_shou_ru: RiZhiYunYingShouRu
      t_ri_zhi_xiao_shou_ri_chang_shi_wu: RiZhiXiaoShouRiChangShiWu
      t_odm_data: OdmData
      t_ri_zhi_yun_ying_yu_ding: RiZhiYunYingYuDing
      t_ri_zhi_yun_ying_huan_fang: RiZhiYunYingHuanFang
      t_customer_he_tong: CustomerHeTong
      t_customer_yu_ding: CustomerYuDing
      t_room_tong_zhu: RoomTongZhu
      t_ri_zhi_yun_ying_tong_zhu: RiZhiYunYingTongZhu
      t_customer_tui_zu: CustomerTuiZu
      t_customer_bao_xiu: CustomerBaoXiu
      t_customer_bao_jie: CustomerBaoJie
      t_customer_qian_fei: CustomerQianFei
      t_chu_zu: ChuZu
      t_tou_su: TouSu
      t_gong_qu_dian: GongQuDian
      t_fu_kuan_tong_zhi: FuKuanTongZhi
      t_shou_ru: ShouRu








  # 表对象对应类后缀，词尾
    poPostfix:
  #  查询对象后缀
    queryPostfix: Query
  #  删除对象后缀
    removePostfix: Remove
  #  修改对象后缀
    modifyPostfix: Modify
  #  Provider对象
    providerPostfix: Provider
  # 持久类后缀; 词尾
    mapperPostfix: Mapper
  # Manager接口类后缀; 词尾
    managerPostfix: Manager
  # Manager实现类后缀; 词尾
    managerImplPostfix: ManagerImpl
  # 业务接口类后缀; 词尾
    servicePostfix: Service
  # 业务类后缀; 词尾
    serviceImplPostfix: ServiceImpl
  # Controller后缀; 词尾
    controllerPostfix: Controller


#启动图形界面
spring.banner.location:  zhsit.cn.txt
